---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm
  #namespace: prod-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
        - name: npm
          image: npm
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-node
  #namespace: prod-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-node
  template:
    metadata:
      labels:
        app: frontend-node
    spec:
      containers:
        - name: frontend-node
          image: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 3
          ports:
            - containerPort: 80              
